#!/bin/bash

# do not forget to execute "module load likwid" !

CORE="0"
PROGRAM="naive 2048x2048-1 2048x2048-2 C.out"
echo Profiling program $PROGRAM on core $CORE

echo ================================================================================
echo

for i in FLOPS_DP L2 L2CACHE
do
	echo Measuring performance for event group $i \
	     using the marker api...

	likwid-perfctr -C $CORE -g $i -m ./$PROGRAM 

	echo ================================================================================
	echo
done
